#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export POSE_BACKEND="${POSE_BACKEND:-rknn}"
export RKNN_POSE_PIPELINE="${RKNN_POSE_PIPELINE:-yolov8_rtmpose}"
export RKNN_POSE_MODEL="${RKNN_POSE_MODEL:-/home/elf/models/yolov8n-pose.rknn}"
export RKNN_RTMPOSE_MODEL="${RKNN_RTMPOSE_MODEL:-rknn/rtmpose_fp16.rknn}"
export RK_CAMERA_DEVICE="${RK_CAMERA_DEVICE:-/dev/v4l/by-id/usb-icSpring_icspring_camera-video-index0}"
export RK_CAMERA_OPEN_MODE="${RK_CAMERA_OPEN_MODE:-opencv}"
export RK_CAMERA_GST_FORMAT="${RK_CAMERA_GST_FORMAT:-MJPG}"
export RK_CAMERA_FPS="${RK_CAMERA_FPS:-30}"
export RK_CAMERA_WIDTH="${RK_CAMERA_WIDTH:-640}"
export RK_CAMERA_HEIGHT="${RK_CAMERA_HEIGHT:-480}"
export RKNN_STREAM_WIDTH="${RKNN_STREAM_WIDTH:-640}"
export RKNN_STREAM_HEIGHT="${RKNN_STREAM_HEIGHT:-360}"
export RKNN_PREVIEW_FPS="${RKNN_PREVIEW_FPS:-3}"
export RKNN_POSE_CONF_THRES="${RKNN_POSE_CONF_THRES:-0.35}"
export RKNN_POSE_NMS_THRES="${RKNN_POSE_NMS_THRES:-0.45}"
export RKNN_POSE_KEYPOINT_THRES="${RKNN_POSE_KEYPOINT_THRES:-0.20}"
export RKNN_POSE_MAX_DET="${RKNN_POSE_MAX_DET:-1}"
export RKNN_MAX_POSE_PERSONS="${RKNN_MAX_POSE_PERSONS:-1}"
export RKNN_YOLO_DET_INTERVAL="${RKNN_YOLO_DET_INTERVAL:-8}"
export RKNN_YOLO_DET_CACHE_SECONDS="${RKNN_YOLO_DET_CACHE_SECONDS:-2.0}"
export RKNN_POSE_INTERVAL="${RKNN_POSE_INTERVAL:-1}"
export RKNN_POSE_CACHE_SECONDS="${RKNN_POSE_CACHE_SECONDS:-1.0}"
export RKNN_RTMPOSE_BBOX_EXPAND="${RKNN_RTMPOSE_BBOX_EXPAND:-1.35}"
export RKNN_RTMPOSE_BBOX_TOP_EXPAND="${RKNN_RTMPOSE_BBOX_TOP_EXPAND:-0.20}"
export RKNN_RTMPOSE_DEBUG_CROP_EVERY="${RKNN_RTMPOSE_DEBUG_CROP_EVERY:-0}"
export RKNN_RTMPOSE_DEBUG_CROP_PATH="${RKNN_RTMPOSE_DEBUG_CROP_PATH:-outputs/debug_rtmpose_crop.jpg}"
export RKNN_MIN_PERSON_BOX_HEIGHT_RATIO="${RKNN_MIN_PERSON_BOX_HEIGHT_RATIO:-0.42}"
export RKNN_MIN_PERSON_BOX_AREA_RATIO="${RKNN_MIN_PERSON_BOX_AREA_RATIO:-0.08}"
export REHAB_KEYFRAME_EVERY_N="${REHAB_KEYFRAME_EVERY_N:-3}"
export RKNN_FAST_PREVIEW="${RKNN_FAST_PREVIEW:-1}"
export RKNN_FAST_FRAME_DATA="${RKNN_FAST_FRAME_DATA:-0}"
export RKNN_FIXED_STRICT_LEG_VISIBILITY="${RKNN_FIXED_STRICT_LEG_VISIBILITY:-1}"
export RKNN_FIXED_LEG_VISIBILITY_THRESHOLD="${RKNN_FIXED_LEG_VISIBILITY_THRESHOLD:-0.30}"
export RKNN_FIXED_DRAW_VISIBILITY_THRESHOLD="${RKNN_FIXED_DRAW_VISIBILITY_THRESHOLD:-0.35}"
export RK_CAMERA_FAIL_DISPLAY_THRESHOLD="${RK_CAMERA_FAIL_DISPLAY_THRESHOLD:-30}"

if [[ ! -f "$RKNN_POSE_MODEL" ]]; then
  echo "RKNN_POSE_MODEL not found: $RKNN_POSE_MODEL" >&2
  echo "Run scripts/prepare_yolov8_pose_model.sh first, or set RKNN_POSE_MODEL." >&2
  exit 2
fi

if [[ ! -f "$RKNN_RTMPOSE_MODEL" ]]; then
  echo "RKNN_RTMPOSE_MODEL not found: $RKNN_RTMPOSE_MODEL" >&2
  exit 2
fi

echo "Using YOLOv8 person box RKNN model: $RKNN_POSE_MODEL"
echo "Using RTMPose RKNN model: $RKNN_RTMPOSE_MODEL"
echo "Camera mode ${RK_CAMERA_OPEN_MODE}; ${RK_CAMERA_WIDTH}x${RK_CAMERA_HEIGHT}@${RK_CAMERA_FPS}; stream ${RKNN_STREAM_WIDTH}x${RKNN_STREAM_HEIGHT}"
echo "YOLO detector interval: ${RKNN_YOLO_DET_INTERVAL} frame(s); det cache: ${RKNN_YOLO_DET_CACHE_SECONDS}s; pose interval: ${RKNN_POSE_INTERVAL} frame(s)"
echo "RTMPose bbox expand: ${RKNN_RTMPOSE_BBOX_EXPAND}; top expand: ${RKNN_RTMPOSE_BBOX_TOP_EXPAND}; debug crop every: ${RKNN_RTMPOSE_DEBUG_CROP_EVERY}"
python3 prescription/banzi/record_prescription_http.py
