#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export POSE_BACKEND="${POSE_BACKEND:-rknn}"
export RKNN_POSE_PIPELINE="${RKNN_POSE_PIPELINE:-rtmpose_fixed}"
export RKNN_RTMPOSE_MODEL="${RKNN_RTMPOSE_MODEL:-rknn/rtmpose_fp16.rknn}"
export RKNN_RTMPOSE_FIXED_BBOX="${RKNN_RTMPOSE_FIXED_BBOX:-80,20,560,470}"
export RKNN_RTMPOSE_FIXED_BBOX_MODE="${RKNN_RTMPOSE_FIXED_BBOX_MODE:-absolute}"
export RKNN_RTMPOSE_FIXED_SCORE="${RKNN_RTMPOSE_FIXED_SCORE:-1.0}"
export RK_CAMERA_DEVICE="${RK_CAMERA_DEVICE:-/dev/v4l/by-id/usb-icSpring_icspring_camera-video-index0}"
export RK_CAMERA_OPEN_MODE="${RK_CAMERA_OPEN_MODE:-opencv}"
export RK_CAMERA_GST_FORMAT="${RK_CAMERA_GST_FORMAT:-MJPG}"
export RK_CAMERA_FPS="${RK_CAMERA_FPS:-30}"
export RK_CAMERA_WIDTH="${RK_CAMERA_WIDTH:-640}"
export RK_CAMERA_HEIGHT="${RK_CAMERA_HEIGHT:-480}"
export RKNN_STREAM_WIDTH="${RKNN_STREAM_WIDTH:-640}"
export RKNN_STREAM_HEIGHT="${RKNN_STREAM_HEIGHT:-360}"
export RKNN_PREVIEW_FPS="${RKNN_PREVIEW_FPS:-3}"
export RKNN_POSE_KEYPOINT_THRES="${RKNN_POSE_KEYPOINT_THRES:-0.20}"
export RKNN_MIN_PERSON_BOX_HEIGHT_RATIO="${RKNN_MIN_PERSON_BOX_HEIGHT_RATIO:-0.42}"
export RKNN_MIN_PERSON_BOX_AREA_RATIO="${RKNN_MIN_PERSON_BOX_AREA_RATIO:-0.08}"
export REHAB_KEYFRAME_EVERY_N="${REHAB_KEYFRAME_EVERY_N:-3}"
export RKNN_FAST_PREVIEW="${RKNN_FAST_PREVIEW:-1}"
export RKNN_FAST_FRAME_DATA="${RKNN_FAST_FRAME_DATA:-1}"
export RKNN_RTMPOSE_DRAW="${RKNN_RTMPOSE_DRAW:-0}"
export RKNN_DRAW_FIXED_BBOX="${RKNN_DRAW_FIXED_BBOX:-1}"
export RKNN_FIXED_STRICT_LEG_VISIBILITY="${RKNN_FIXED_STRICT_LEG_VISIBILITY:-1}"
export RKNN_FIXED_LEG_VISIBILITY_THRESHOLD="${RKNN_FIXED_LEG_VISIBILITY_THRESHOLD:-0.30}"
export RKNN_FIXED_DRAW_VISIBILITY_THRESHOLD="${RKNN_FIXED_DRAW_VISIBILITY_THRESHOLD:-0.35}"
export RK_CAMERA_FAIL_DISPLAY_THRESHOLD="${RK_CAMERA_FAIL_DISPLAY_THRESHOLD:-30}"

if [[ ! -f "$RKNN_RTMPOSE_MODEL" ]]; then
  echo "RKNN_RTMPOSE_MODEL not found: $RKNN_RTMPOSE_MODEL" >&2
  exit 2
fi

echo "Using RTMPose fixed ROI RKNN model: $RKNN_RTMPOSE_MODEL"
echo "Fixed bbox: $RKNN_RTMPOSE_FIXED_BBOX; camera ${RK_CAMERA_WIDTH}x${RK_CAMERA_HEIGHT}@${RK_CAMERA_FPS}; stream ${RKNN_STREAM_WIDTH}x${RKNN_STREAM_HEIGHT}"
python3 prescription/banzi/record_prescription_http.py
